### ISSUE TITLE
Issue with reverse lists

### ISSUE THREAD

**Issue by iCyberon** [ky1vstar/cupertino_interactive_keyboard#2]
Doesn't behave as expected when working with reverse lists, the end result looks like velocity has been increased by 2, i.e. for each pixel the keyboard goes down, list scrolls 2 pixels.

**Comment by ky1vstar** [comment]
@iCyberon thanks for the report! Looks like I found a solution to this issue - ideally, it should be fixed in https://github.com/ky1vstar/cupertino_interactive_keyboard/commit/601c2b4c6cf8476d6889982373b8f86bfe178b1d.

Can you add this to your `pubspec.yaml` and check whether this fixes the problem?

```yaml
dependency_overrides:
  cupertino_interactive_keyboard:
    git:
      url: https://github.com/ky1vstar/cupertino_interactive_keyboard.git
      ref: 601c2b4
```
